project:
  type: book
  output-dir: docs

book:
  title: "Reduced Meiotic Crossing Over Linked to Impaired Sperm Motility"
  author: "Lei Yu"
  date: "05/10/2024"
  chapters:
    - index.qmd
    - section_1_data_process.qmd
    - section_2_aneuploidy_test.qmd
    - section_3_prepare_data_for_Hapi.qmd
    - section_4_run_Hapi.qmd
    - section_5_filter_HAPI_output.qmd
    - section_6_compare_CO.qmd
    - section_7_CO_and_clinical_outcome_association_study.qmd
    - section_8_CO_whole_genome_association_study.qmd
    - section_9_transcriptome.qmd
 
bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

