# Introduction

This is a R document for the project *Reduced Meiotic Crossing Over Linked to Impaired Sperm Motility*.

# Abstract

Meiotic crossing over, governed by a complex genetic system, remains inadequately understood, particularly in its relation to gamete vitality. This study compares crossover frequencies in males with normal fertility (NF) and those with asthenospermia (AS), a condition characterized by reduced sperm motility and reveals a significantly reduced crossover rate in the AS group, along with an increased propensity for generating aneuploid sperm compared to the NF group. The profiling of the crossover events not only identifies hotspots in male gamete genomes but also indicates a decline in the crossover rate with age in both NF and AS groups, correlating with key sperm movement characteristics. Genome-wide association studies pinpoint 119 crossover-linked genes, showing enrichment in energy metabolism and DNA-related activities, crucial to meiosis. Transcriptome analysis of an independent cohort validated essential genes, including SPATA18 – a recognized participant in spermatogenesis. Our results highlight  the potential impact of energy transformation deficiency on recombination obstacles as well as impaired sperm motility. Furthermore, this research establishes a methodological paradigm for studying meiotic crossovers in males, with potential applications in clinical settings such as detecting crossover disorders and monitoring the efficacy of treatments for asthenospermia patients.

Keywords: aneuploidy; asthenospermia; crossing over; genome-wide association study; meiosis; single sperm cell sequencing

![Workflow for Comprehensive Analysis of Sperm Motility Characteristics and Recombination. In this study, we outline the comprehensive analysis workflow for assessing sperm motility characteristics and recombination. (A) Genome Profile Phase. During the genome profile phase, we collected blood samples and 4-5 sperm samples from asthenospermia donors (n = 19) and normal donors (n = 11). Bulk sequencing of blood samples was conducted at an approximate depth of 10x, while single-cell sequencing was performed on sperm cells at a depth of 1x. For each donor, fastq files from bulk blood sequencing and 4-5 sperm single-cell fastq files were generated as part of the genome profiling phase. (B) Individual-Level Crossover Detection Phase. During the individual-level crossover detection phase, the Genome Analysis Toolkit (GATK) genotyping pipeline was employed to obtain the genotypes of both blood and sperm samples for each donor. Heterogeneous loci positions were extracted from the blood genotype profile and subsequently utilized as a reference for HAPI, enabling the identification of crossover events in each sperm sample. By the conclusion of this phase, both the blood genotype profile and the crossover event profiles for each sperm sample were generated. (C) Transcriptome Profiling Phase. In this phase, a second cohort consisting of sperm samples from asthenospermia donors (n = 7) and normal donors (n = 6) was collected. RNA-sequencing (RNA-seq) was performed to obtain the gene expression profiles of these samples. (D) Downstream Statistics Analysis Phase. In this phase, several key analyses were carried out, including crossover hotspot analysis, a comparison of crossovers between asthenospermia and normal sperm, an investigation into crossover frequency-associated loci, and a comparison study of critical genes.](Figures/s1.png)

# Needed Packages

Load the needed packages. Below are the packages need in this documents.

```{r, class.source = "RCode", eval=F}

library(data.table)
library(dplyr)
library(stringr)
library(ggplot2)
library(karyoploteR)
library(tibble)
library(tidyr)
library(Hapi)
library(HMM)
library(tidyverse)
library(purrr)
library(vcfR)
library(DESeq2)
library(ggplot2)
library(ggrepel)
library(biomaRt)
library(stringr)
library(tidyverse)
library(reshape2)
library(ggpubr)
library(ggExtra)
library(ggbeeswarm)
library(GGally)
library(regioneR)
library(CopyNumberPlots)
library(ggpmisc)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(scales)
library(ggthemes)
```
